[tox]
envlist =
    lint,
    python3.11,
    python3.12
    python3.13,
    python3.14

[testenv]
passenv = APP_ENV
skip_install = true
allowlist_externals = *poetry
# Poetry may not be in the path (e.g. if running in Jenkins)
# In that case, assume the location is in the POETRY environment variable
setenv =
    POETRY = {env:POETRY:poetry}
    COVERAGE_FILE = .coverage_db_{envname}
commands_pre = {env:POETRY} install --all-extras
commands = {env:POETRY} run pytest --color=yes --cov=rddthreshtune --cov-report html:htmlcov_{envname} --cov-report term --cov-report xml:coverage_{envname}.xml

[testenv:lint]
commands =
    {env:POETRY} run isort --version
    {env:POETRY} run isort --check-only --df .
    {env:POETRY} run black --version
    {env:POETRY} run black --check --diff .
;    {env:POETRY} run mypy --version
;    {env:POETRY} run mypy .
    {env:POETRY} run ruff --version
    {env:POETRY} run ruff check .
